### ISSUE TITLE
The validation of DateTime is not ISO8601 compliant

### ISSUE THREAD

**Issue by xletohic-thefork** [Saeris/graphql-scalars#19]
Given a valid ISO8601 date time string `2018-05-31T10:30:00Z` the DateTime validation transform it as `2018-05-31T10:30:000Z` (with a new zero at the end) which should not happen:

[https://en.wikipedia.org/wiki/ISO_8601](https://en.wikipedia.org/wiki/ISO_8601)

**Comment by Saeris** [comment]
Hey! Sorry for the delayed response. I don't believe this is a problem necessarily with this library specifically, but is instead a bug with Joi's date validation which this library uses. It may be that there has since been an update to Joi that addresses this that perhaps is not within the version range of this project's dependencies, though it doesn't look like Greenkeeper has issued any PRs for an update to Joi.
